server:
  port: 9988
  servlet:
    context-path: /spring
  tomcat:
    basedir: app/SpringManager/tmp

spring:
  application:
    name: spring

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?useUnicode=true&characterEncoding=utf-8&&useSSL=false&&serverTimezone=Asia/Shanghai&&allowMultiQueries=true
    username: root
    password: password
    #保证服务稳定
    tomcat:
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000

  jpa:
    #显示sql语句
    show-sql: true
    database: mysql
    open-in-view: true

  #日期格式配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#是否开启swagger
swagger:
  enabled: true
#日志输出配置
logging:
  path: C:/春天造型管理系统/log/
  file:
    max-size: 10MB