server:
  port: 9876

spring:
  application:
    name: spring

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8&&useSSL=false&&serverTimezone=Asia/Shanghai&&allowMultiQueries=true
    username: root
    password: password
    platform: mysql
    schema: classpath:spring.sql
    continue-on-error: false
    #保证服务稳定
    tomcat:
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000

  jpa:
    #显示sql语句
    show-sql: true
    database: mysql
    open-in-view: true
    hibernate:
      ddl-auto: none
  #日期格式配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#是否开启swagger
swagger:
  enabled: true